FROM node:24-alpine

RUN apk update && apk add --no-cache bash

RUN adduser -D runner
WORKDIR /home/runner/kernel

COPY ./package.json ./
ENV COREPACK_HOME=/home/runner/corepack
RUN corepack enable && corepack install

COPY ./.yarnrc.yml ./
RUN yarn install

ARG NEXT_PUBLIC_LEAP360_API_BASE_URL
ENV NEXT_PUBLIC_LEAP360_API_BASE_URL=${NEXT_PUBLIC_LEAP360_API_BASE_URL}
COPY . .
RUN yarn build

CMD ["bash", "-c", "exec yarn start --hostname 0.0.0.0 --port ${PORT}"]
